# Parts of Language Service
commons-atom
commons-node
hyperclick
nuclide-analytics
nuclide-busy-signal
nuclide-code-format
nuclide-code-highlight
nuclide-context-view
nuclide-datatip
nuclide-definition-hyperclick
nuclide-definition-service
nuclide-definition-service-common
nuclide-diagnostics-common
nuclide-diagnostics-datatip-provider
nuclide-diagnostics-provider-base
nuclide-diagnostics-store
nuclide-diagnostics-ui
nuclide-flow
nuclide-flow-common
nuclide-flow-rpc
nuclide-language-service
nuclide-language-service-rpc
nuclide-logging
nuclide-node-transpiler
nuclide-open-files
nuclide-open-files-rpc
nuclide-outline-view
nuclide-textedit
nuclide-type-coverage
nuclide-type-hint
nuclide-ui
nuclide-workspace-view-locations
nuclide-workspace-views
nuclide-vscode-language-service

# Unrelated packages easier to pull in than to fix.
nuclide-debugger-interfaces
nuclide-test-helpers
pkg/nuclide-debugger-base
pkg/nuclide-home
pkg/nuclide-nux
pkg/nuclide-distraction-free-mode
